version: DEVSPACE-VERSION # required
name: PROJECT-NAME # required

pipelines:
  dev:
    run: |-
      create_deployments --all
      start_dev APP-NAME

  deploy:
    run: |-
      build_images --all -t $(git describe --always)
      create_deployments --all

  images:
    APP-NAME:
      image: IMAGE-URL
      dockerfile: PATH-TO-DOCKERFILE

  deployments:
    APP-NAME:
      helm:
        chart:
          name: CHART-NAME
          repo: CHART-URL
        values:
          containers:
            - image: IMAGE-REPO/APP-NAME
          service:
            ports:
              - port: PORT
      kubectl:
        manifests:
          - PATH-TO-MANIFEST
          - PATH-TO-MANIFEST
          - ...